### ISSUE TITLE
How do you like this solution so far?

### ISSUE THREAD

**Issue by TomasVotruba** [lastzero/test-tools#3]
Hi,

I just wanted to ask about your experience with this solution.

- How long do you use that?
- How fast is it?
- What are some disadvantages of it?

I think this might be the ease-intro to unit testing. 

Because real code is: dependency injection with container.
and against testing code: manually passing everything - step back to static.

Having *DI : DI* in both real code and testing could make it more logical, understandable and thus usable.

**Comment by lastzero** [comment]
Hi Tomas,

I'm using it for my client projects since I pushed it to GitHub in 2013 (check out https://lastzero.net/about/ or LinkedIn to see what clients I've been working for). This library  tremendously improves productivity. Never had any performance issues. You got it right: It doesn't make sense to have two different concepts for dependency injection in "real" and test code.

Thanks a lot for your pull requests, I'm going to review them shortly!

Michael
